### PR TITLE
Support bytestring-0.11

### PR DESCRIPTION
**Pull request by Bodigrim**
If this looks too involved, alternatively you can just drop support of GHC 7.10 with a revision: for GHC 8.0+ `bytestring-0.11` provides a backward compatible pattern synonym `PS`. **Upd.:** But in such scenario earlier releases need to be revised with `bytestring < 0.11`, otherwise `cabal` will choose to build them and choke.

### CODE REVIEW

**Comment by Bodigrim** [comment]
(Windows build on CI is failing for an independent reason, I believe)

**Comment by kazu-yamamoto** [comment]
@Bodigrim Thank you for letting me know this. I would like to drop support for GHC 7 and keep the code unchanged. Does the following work?

- Edit the metadata of network-byte-order 0.1.6 (bytestring < 0.11)
- Release network-byte-order 0.1.7 with base >= 4.9.

**Comment by Bodigrim** [comment]
For a new release the best amendment is to add
```
if impl(ghc < 8.0):
  build-depends:
    bytestring < 0.11
```
This way your package is still buildable with GHC 7.10, and with bytestring-0.11, but not with both at the same time. This is somewhat better than just putting `base >= 4.9`.

----

Revising `0.1.6` only with `bytestring < 0.11` will not improve anything: `cabal` will happily pull `network-byte-order-0.1.5` or earlier. Unless you are happy to revise all `0.1.*` releases, you can save yourself time and revise none with the same practical effect. 

There are tools to revise all releases at once, if you are interested to give it a try.

**Comment by kazu-yamamoto** [comment]
OK. Since I don't want to support GHC 7.x anymore, I would like to add "base >= 4.9" to all releases. Would you tell me the tool name?

**Comment by Bodigrim** [comment]
The tool is here: https://github.com/hackage-trustees/hackage-cli

It has not been updated for a while, so one needs GHC 8.6 to run it:

```
ghcup install ghc --set 8.6
git clone git@github.com:hackage-trustees/hackage-cli.git
cd hackage-cli
cabal install 
```

Now download cabal files:

```
mkdir network-byte-order
cd network-byte-order
hackage-cli pull-cabal network-byte-order
```

Add new bound for `base` (alternatively use `awk`):

```
hackage-cli add-bound base '>= 4.9' *.cabal
```

Put your Hackage credentials into `~/.netrc`, like `machine hackage.haskell.org login MyUserName password TrustNo1`. Then upload revised cabal files (potentially with `--publish` and `--incr-rev`, but do a dry run first): 

```
hackage-cli push-cabal *.cabal
```

Here is an example of a similar bulk modification: https://github.com/haskell/bytestring/issues/285

Hope it helps.

**Comment by Bodigrim** [comment]
@kazu-yamamoto did you possibly have a chance to make up your mind? I'm sorry to nudge so soon, I just have some further work to do depending on your choices here.

**Comment by kazu-yamamoto** [comment]
@Bodigrim  I'm sorry but due to my poor English I cannot interpret "make up your mind". I'm planning to modify all metadata on Hackage with your approach. But its priority is middle since I have some jobs of high priority at this moment.

**Comment by kazu-yamamoto** [comment]
@Bodigrim Done for network-byte-order. Would you check?

**Comment by Bodigrim** [comment]
Thanks, closing.

**Pull request closed without merging**
